### ISSUE TITLE
error during amass config file load 

### ISSUE THREAD

**Issue by saransh121** [remonsec/SEF#1]
hey buddy,
i face a problem during the passive scan of SEF due to amass -config issue,
function Passive() {
    echo "[=] Running Passive Enumeration"
    subfinder -d $domain -o subfinder.txt &>/dev/null
    assetfinder --subs-only $domain | sort -u > assetfinder.txt &>/dev/null
    **amass enum -passive -norecursive -noalts -d $domain -config $amass_config -o amass.txt &>/dev/null**
    findomain -t $domain -u findomain.txt &>/dev/null
    cat subfinder.txt assetfinder.txt amass.txt findomain.txt | grep -F ".$domain" | sort -u > passive.txt
    rm subfinder.txt assetfinder.txt amass.txt findomain.txt
}

intially you declar : amass_config=~/.config/amass/config.ini

so there is no need of -config flag,

here 
function Passive() {
    echo "[=] Running Passive Enumeration"
    subfinder -d $domain -o subfinder.txt &>/dev/null
    assetfinder --subs-only $domain | sort -u > assetfinder.txt &>/dev/null
    **amass enum -passive -norecursive -noalts -d $domain $amass_config -o amass.txt &>/dev/null**
    findomain -t $domain -u findomain.txt &>/dev/null
    cat subfinder.txt assetfinder.txt amass.txt findomain.txt | grep -F ".$domain" | sort -u > passive.txt
    rm subfinder.txt assetfinder.txt amass.txt findomain.txt
}

this fix my issue , if this only issue for my system then it's ok, beause this fixed work perfectly for me,
but if actually this is a issue you might change the script a bit,

regards saransh

**Comment by KathanP19** [comment]
Hey saransh,
I think it's the only issue for your system as in the official guide of amass you need to use `-config` to set the file.  
Check here https://github.com/OWASP/Amass/blob/master/doc/user_guide.md
