### ISSUE TITLE
after installing through install.sh , this tool doesnt work at all

### ISSUE THREAD

**Issue by SHARWAN-2002** [remonsec/SEF#3]

**Comment by SHARWAN-2002** [comment]
it shows like sef command not found

**Comment by remonsec** [comment]
install.sh is to install the dependencies. 
you can run it like
```
cd SEF
bash sef -d site.com --quick -o site
```
or just send the bash script in your bin folder
```
cp sef /usr/local/bin
```
Now sef will work from anywhere you want in your terminal 
```
sef -d site.com --quick -o site
```
