### ISSUE TITLE
i'm using Docker and whenever i type sef in command line , i get a error like the picture below

### ISSUE THREAD

**Issue by SHARWAN-2002** [remonsec/SEF#4]
![Capture](https://user-images.githubusercontent.com/67257718/102706014-fca23480-42b3-11eb-8041-02bcfe905eaa.PNG)

**Comment by SHARWAN-2002** [comment]
i don't know what type of error , is this but i often get this error whenever i tried to use Tools which was written in GO language

**Comment by remonsec** [comment]
The error you are facing is not for SEF, it may be your system configuration. 
I don't well about it, But can confirm that error is not coming from SEF
So just closing the issue 
Hope you will get the fix soon
